### ISSUE TITLE
image 上传失败

### ISSUE THREAD

**Issue by guoxinliang** [laravel-admin-extensions/config#14]
value字段 将textarea改为 image  上传失败 结果为“phpBF96.tmp”  
固定id 或者 name使用image组件  上传不成功

**Comment by guoxinliang** [comment]
$content->body($this->form($id)->edit($id));
            if($id){
                $form->image('content','值')->uniqueName()->rules('required');
            }else{
                $form->textarea('content','值')->uniqueName()->rules('required');
            }
上传失败， 提交后用的是textarea验证

**Comment by guoxinliang** [comment]
if($id==1){
       $form->image('content','值')->uniqueName()->rules('required');
}else{
       if(request('config')==1){
                $form->image('content','值')->uniqueName()->rules('required');
        }else{
                $form->textarea('content','值')->rules('required');
         }
 }

最后这样解决了。

**Comment by z-song** [comment]
是这个扩展的问题还是laravel-admin的问题？

**Comment by guoxinliang** [comment]
@z-song  laravel-admin的问题
