### ISSUE TITLE
前端表头如何修改？

### ISSUE THREAD

**Issue by johnson1616** [laravel-admin-extensions/config#20]
能否重写ConfigController

**Comment by z-song** [comment]
什么意思?

**Comment by johnson1616** [comment]
就是这里

![image](https://user-images.githubusercontent.com/37334321/45805230-cfd7cf00-bcf0-11e8-9e18-dd2aef74e028.png)
如何修改

**Comment by z-song** [comment]
不支持，你可以参考代码自己实现一个
