### ISSUE TITLE
not able to install in latest laravel-admin version

### ISSUE THREAD

**Issue by azinkey** [laravel-admin-extensions/config#30]
PHP version: 7.2
laravel version: 6.2
laravel-admin: 1.7.8

**composer require laravel-admin-ext/config**

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel-admin-ext/config v1.0.3
    - Installation request for laravel/framework (locked at v6.6.1, required as ^6.2) -> satisfiable by laravel/framework[v6.6.1].
    - Conclusion: don't install laravel-admin-ext/config v1.0.2
    - Conclusion: don't install laravel-admin-ext/config v1.0.1
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.8].
    - Can only install one of: encore/laravel-admin[v1.7.8, 1.5.x-dev].
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.8].
    - laravel-admin-ext/config v1.0 requires encore/laravel-admin 1.5.* -> satisfiable by encore/laravel-admin[1.5.x-dev].
    - Installation request for laravel-admin-ext/config ^1.0 -> satisfiable by laravel-admin-ext/config[v1.0, v1.0.1, v1.0.2, v1.0.3].
    - Installation request for encore/laravel-admin (locked at v1.7.8, required as ^1.7) -> satisfiable by encore/laravel-admin[v1.7.8].

**Comment by z-song** [comment]
New version released
